name = "roots-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2021-2022, Jacob Williams"
license = "BSD-3"
description = "A library for finding the roots of continuous scalar functions of a single real variable"
homepage = "https://github.com/jacobwilliams/roots-fortran"
keywords = ["root"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[dev-dependencies]
pyplot-fortran = { git = "https://github.com/jacobwilliams/pyplot-fortran", tag = "3.2.0" }

[library]
source-dir = "src"

[install]
library = true